[colors]
[colors.primary]
background = "#f6f1e9"
foreground = "#241803"

[colors.normal]
black   = "#f6f1e9"
red     = "#936100"
green   = "#007881"
yellow  = "#8c509a"
blue    = "#763900"
magenta = "#00606c"
cyan    = "#6e217f"
white   = "#241803"

[colors.bright]
black   = "#86837c"
red     = "#bc8400"
green   = "#2e9ea9"
yellow  = "#b66dcc"
blue    = "#9f5914"
magenta = "#2a8494"
cyan    = "#973cb1"
white   = "#433617"

[colors.cursor]
text   = "#f6f1e9"
cursor = "#241803"
