# Background and foreground colors
background = #f6f1e9
foreground = #241803

# Standard colors
palette = 0=#f6f1e9
palette = 1=#936100
palette = 2=#007881
palette = 3=#8c509a
palette = 4=#763900
palette = 5=#00606c
palette = 6=#6e217f
palette = 7=#241803

# Bright colors
palette = 8=#86837c
palette = 9=#bc8400
palette = 10=#2e9ea9
palette = 11=#b66dcc
palette = 12=#9f5914
palette = 13=#2a8494
palette = 14=#973cb1
palette = 15=#433617
