$color = rgba(246, 241, 233, 1)
$inner_color = rgba(246, 241, 233, 0.66)
$outer_color = rgba(0, 96, 108, 1)
$font_color = rgba(36, 24, 3, 1)
$placeholder_color = rgba(36, 24, 3, 0.7)
$check_color = rgba(110, 33, 127, 1)
